version: '3'
services:
  auth-db:
    image: postgres:latest
    container_name: auth-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api_login_users_db
    ports:
      - "5432:5432"
    networks:
      - redelocal
  product-db:
    image: postgres:latest
    container_name: product-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api_products_db
    ports:
      - "5433:5432"
    networks:
      - redelocal 
  cart-db:
    image: postgres:latest
    container_name: cart-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api_carts_db
    ports:
      - "5434:5432"
    networks:
      - redelocal
  auth-app:
    build:
      context:'./tc5-login-users'
      dockerfile: Dockerfile
    image: auth-app:latest
    container_name: auth-app
    ports:
      - "8080:8080"
    networks:
      - redelocal
    depends_on:
      - auth-db
  product-app:
    build:
      context: './tc5-api-products'
      dockerfile: Dockerfile
    image: product-app:latest
    container_name: product-app
    environment:
      - SPRING_SERVER_PORT=8081
      - SPRING_DATA_SOURCE_URL=jdbc:postgresql://product-db:5434/api_carts_db
      - SPRING_DATA_SOURCE_USERNAME=admin
      - SPRING_DATA_SOURCE_PASSWORD=admin
      - SPRING_JWT_SECRET=YmF0bWFuIGJhdG1hbiBiYXRtYW4=
    ports:
      - "8081:8081"
    networks:
      - redelocal
    depends_on:
      - product-db
  cart-app:
    build:
      context: './tc5-api-carts'
      dockerfile: Dockerfile
    image: cart-app:latest
    container_name: cart-app
    environment:
      - SPRING_SERVER_PORT=8082
      - SPRING_DATA_SOURCE_URL=jdbc:postgresql://cart-db:5434/api_carts_db
      - SPRING_DATA_SOURCE_USERNAME=admin
      - SPRING_DATA_SOURCE_PASSWORD=admin
      - SPRING_JWT_SECRET=YmF0bWFuIGJhdG1hbiBiYXRtYW4=
      - SPRING_URL_PRODUCT=http://product-app:8081
    ports:
      - "8082:8082"
    networks:
      - redelocal
    depends_on:
      - cart-db
  payment-app:
    build:
      context: './tc5-api-payments'
      dockerfile: Dockerfile
    image: payment:latest
    container_name: payment-app
    environment:
      - SPRING_SERVER_PORT=8083
      - SPRING_JWT_SECRET=YmF0bWFuIGJhdG1hbiBiYXRtYW4=
      - SPRING_URL_PRODUCT=http://cart-app:8082
    ports:
      - "8083:8083"
    networks:
      - redelocal

networks:
  redelocal:

volumes:
  postgres-data:
