version: '3'
services:
  auth-db:
    image: postgres:latest
    container_name: auth-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api_login_users_db
    ports:
      - "5432:5432"
    networks:
      - redelocal
  product-db:
    image: postgres:latest
    container_name: product-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api_products_db
    ports:
      - "5433:5432"
    networks:
      - redelocal 
  cart-db:
    image: postgres:latest
    container_name: cart-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api_cart_db
    ports:
      - "5434:5432"
    networks:
      - redelocal
networks:
  redelocal:

volumes:
  postgres-data:
