version: '3'
services:
  auth-db:
    image: postgres:latest
    container_name: auth-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api_login_users_db
    ports:
      - "5432:5432"
    networks:
      - redelocal
  product-db:
    image: postgres:latest
    container_name: product-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api_products_db
    ports:
      - "5433:5432"
    networks:
      - redelocal 
  cart-db:
    image: postgres:latest
    container_name: cart-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api_carts_db
    ports:
      - "5434:5432"
    networks:
      - redelocal
  auth-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: auth-app:latest
    container_name: auth-app
    ports:
      - "8080:8080"
    networks:
      - redelocal
    depends_on:
      - auth-db
  product-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: product-app:latest
    container_name: product-app
    ports:
      - "8081:8080"
    networks:
      - redelocal
    depends_on:
      - product-db
  cart-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cart-app:latest
    container_name: cart-app
    ports:
      - "8082:8080"
    networks:
      - redelocal
    depends_on:
      - cart-db
  payment-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: payment:latest
    container_name: payment-app
    ports:
      - "8083:8080"
    networks:
      - redelocal

networks:
  redelocal:

volumes:
  postgres-data:
