spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  application:
    name: tc5-api-cart

  data:
    web:
      pageable:
        one-indexed-parameters: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATA_SOURCE_URL}
    username: ${SPRING_DATA_SOURCE_USERNAME}
    password: ${SPRING_DATA_SOURCE_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db/migration
    fail-on-missing-locations: true
  jpa:
    show-sql: true
    open-in-view: false

server:
  port: ${SPRING_SERVER_PORT}

app-config:
  services:
    cart: ${SPRING_URL_PRODUCT}
  secrets:
    api-secret: ${SPRING_JWT_SECRET:'batman batman batman'}
